version: '3'

services:
  solr:
    image: solr:vo
    container_name: nomisma_solr
    build: ./solr
    volumes:
      - ./docker-solr-data/nomisma/data:/opt/solr/server/solr/nomisma/data
      - ./docker-solr-data/nomisma-fuseki/data:/opt/solr/server/solr/fuseki/data
    ports:
      - "10404:8983"
  web:
    image: numishare:vo
    container_name: nomisma_web
    build: ./web
    volumes:
      - ./docker-nomisma-data/nomisma-data:/usr/local/projects/nomisma-data
      - ./docker-nomisma-data/nomisma:/usr/local/projects/nomisma
      - ./docker-nomisma-data/NUDS:/usr/local/projects/NUDS
    ports:
      - "10400:8080"
    environment:
      JAVA_OPTS: '-server -Djava.awt.headless=true -Xms1G -Xmx1G -XX:MaxPermSize=256m -XX:NewSize=896m -XX:MaxNewSize=896m -Dlog4j.configuration=/usr/local/tomcat/lib/log4j.properties -XX:+UseConcMarkSweepGC -XX:+CMSPermGenSweepingEnabled -XX:+CMSClassUnloadingEnabled'
    depends_on:
      - solr
      - fuseki
  fuseki:
    image: stain/jena-fuseki
    container_name: nomisma_fuseki
    volumes:
      - ./docker-nomisma-data/docker-fuseki-data:/fuseki
    ports:
      - "10408:3030"
